// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uozepbwxmlxajluyccam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvemVwYnd4bWx4YWpsdXljY2FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDUzMDMsImV4cCI6MjA2NDEyMTMwM30.8IqQK2-Bi8LQF54TuftcnqyvUH3wY-jlbRLHK4iH1Ng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);